name: Branch-based Deployment

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      BASE_PATH: /srv/toychat

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set variables
        id: set-vars
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Current branch: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TARGET_DIR=$BASE_PATH/$BRANCH_NAME/app"  >> $GITHUB_ENV
          echo "DEPLOY_DIR=$BASE_PATH/$BRANCH_NAME/deploy"  >> $GITHUB_ENV
          echo "COMPOSE=$BASE_PATH/$BRANCH_NAME/docker/docker-compose.yml"  >> $GITHUB_ENV
          echo "SERVICE_NAME=$BRANCH_NAME" >> $GITHUB_ENV


      - name: Clean old files
        run: |
          echo "Cleaning $TARGET_DIR"
          sudo rm -rf $TARGET_DIR/*
          sudo mkdir -p $TARGET_DIR
          sudo chown -R $(whoami):$(whoami) $TARGET_DIR

      - name: Copy source
        run: |
          echo "Copying source to $TARGET_DIR"
          cp -r ./* $TARGET_DIR/

      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        run: |
          cd $TARGET_DIR
          mvn clean package -DskipTests
          
          cd $DEPLOY_DIR
          if [ -f "app.jar" ]; then
            cp app.jar app.jar.last
            mv app.jar "app.jar.$(date +'%Y%m%d%H%M%S')"
            
          fi

          cp $TARGET_DIR/target/*.jar $DEPLOY_DIR/app.jar
          
          echo "Restarting service $SERVICE_NAME"
          sudo systemctl restart $SERVICE_NAME          

      - name: Health check dev
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "Running health check on port 9093..."
          for i in {1..10}; do
            if curl -fs http://localhost:9093/actuator/health; then
              echo "Health check passed"
              exit 0
            fi
            echo "Waiting for service..."
            sleep 5
          done

          echo "Health check failed"
          
          if [ -f "$DEPLOY_DIR/app.jar.last" ]; then
            echo "Rolling back.."
            mv "$DEPLOY_DIR/app.jar.last" "$DEPLOY_DIR/app.jar"
            sudo systemctl restart $SERVICE_NAME
            echo "Rollback completed $SERVICE_NAME"
            exit 1
          else
            echo "No app.jar.last found. Manual intervention required."
            exit 1
          fi

      - name: Set image tag
        id: vars
        run: |
          DATE=$(date +%Y%m%d)
          COMMIT=$(git rev-parse --short HEAD)
          echo "TAG=${DATE}-${COMMIT}" >> $GITHUB_ENV
          echo "TAG_NAME=${DATE}-${COMMIT}"
                    
      - name: Deploy main
        if: github.ref == 'refs/heads/main'
        env:
         IMAGE_NAME: toychat-main:latest
         LAST_IMAGE_NAME: toychat-main:latest
        run: |
          cd $TARGET_DIR
          
          docker image inspect $IMAGE_NAME > /dev/null 2>&1 && docker tag $IMAGE_NAME $LAST_IMAGE_NAME || echo "No existing image to backup"
          
          docker compose -f $COMPOSE down
          
          docker build -t $IMAGE_NAME .
          docker build -t toychat-main:$TAG .
          

          docker compose -f $COMPOSE up -d --build
          echo "Restarting service $SERVICE_NAME"
          docker image prune -f

      - name: Health check main
        if: github.ref == 'refs/heads/main'
        env:
         IMAGE_NAME: toychat-main:latest
         LAST_IMAGE_NAME: toychat-main:latest        
        run: |
          echo "Running health check on port 9090..."
          for i in {1..10}; do
            if ! curl -fs http://localhost:9090/actuator/health; then
              echo "Health check failed"
              echo "Rolling back.."
              docker compose -f $COMPOSE down
              docker tag $LAST_IMAGE_NAME toychat-main:latest
              docker compose -f $COMPOSE up -d
              echo "Rollback completed $SERVICE_NAME"
              docker image prune -f

              exit 1
            fi  
            echo "Waiting for service..."
            sleep 5
          done
          
      - name: PR build check
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          echo "Pull Request build for main branch - no deployment"
          cd $TARGET_DIR
          mvn clean package -DskipTests
