name: Branch-based Deployment

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      BASE_PATH: /srv/toychat

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set common variables
        id: set-vars
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Current branch: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TARGET_DIR=$BASE_PATH/$BRANCH_NAME/app"  >> $GITHUB_ENV
          echo "DEPLOY_DIR=$BASE_PATH/$BRANCH_NAME/deploy"  >> $GITHUB_ENV
          echo "COMPOSE=$BASE_PATH/$BRANCH_NAME/docker/docker-compose.yml"  >> $GITHUB_ENV
          echo "SERVICE_NAME=$BRANCH_NAME" >> $GITHUB_ENV


      - name: Clean old files
        run: |
          echo "Cleaning $TARGET_DIR"
          sudo rm -rf $TARGET_DIR/*
          sudo mkdir -p $TARGET_DIR
          sudo chown -R $(whoami):$(whoami) $TARGET_DIR

      - name: Copy source
        run: |
          echo "Copying source to $TARGET_DIR"
          cp -r ./* $TARGET_DIR/

      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        run: |
          cd $TARGET_DIR
          mvn clean package -DskipTests
          
          cd $DEPLOY_DIR
          if [ -f "app.jar" ]; then
            cp app.jar app.jar.last
            mv app.jar "app.jar.$(date +'%Y%m%d%H%M%S')"
            
          fi

          cp $TARGET_DIR/target/*.jar $DEPLOY_DIR/app.jar
          
          echo "Restarting service $SERVICE_NAME"
          sudo systemctl restart $SERVICE_NAME          

      - name: Health check dev
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "Running health check on port 9093..."
          for i in {1..10}; do
            if curl -fs http://localhost:9093/actuator/health; then
              echo "Health check passed"
              exit 0
            fi
            echo "Waiting for service..."
            sleep 5
          done

          echo "Health check failed"
          
          if [ -f "$DEPLOY_DIR/app.jar.last" ]; then
            echo "Rolling back.."
            mv "$DEPLOY_DIR/app.jar.last" "$DEPLOY_DIR/app.jar"
            sudo systemctl restart $SERVICE_NAME
            echo "Rollback completed $SERVICE_NAME"
            exit 1
          else
            echo "No app.jar.last found. Manual intervention required."
            exit 1
          fi

      - name: Cleanup dev
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "Cleaning old app.jar files and journal logs"

          cd $DEPLOY_DIR
          ls -1tr app.jar.* | head -n -3 | xargs -r rm -f
          sudo journalctl --vacuum-size=200M
          
      - name: Set main variables
        id: vars
        if: github.ref == 'refs/heads/main'
        env: 
          GITHUB_USER: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          echo "USERNAME=${GITHUB_USER}" >> $GITHUB_ENV
          echo "GHCR_TOKEN=${GHCR_TOKEN}" >> $GITHUB_ENV

          DATE=$(date +%Y%m%d)
          COMMIT=$(git rev-parse --short HEAD)
          echo "TAG=${DATE}-${COMMIT}" >> $GITHUB_ENV
          echo "TAG_NAME=${DATE}-${COMMIT}"
          
          echo "IMAGE_NAME=ghcr.io/${GITHUB_USER}/toychat-main" >> $GITHUB_ENV
          echo "LATEST=latest" >> $GITHUB_ENV
          echo "BACKUP=backup" >> $GITHUB_ENV
                    
      - name: Deploy main
        if: github.ref == 'refs/heads/main'
        run: |
          cd $TARGET_DIR
          
          docker image inspect $IMAGE_NAME:$LATEST > /dev/null 2>&1 && docker tag $IMAGE_NAME:$LATEST $IMAGE_NAME:$BACKUP || echo "No existing image to backup"
          
          docker compose -f $COMPOSE down
          
          #latest
          docker build -t $IMAGE_NAME:$LATEST .
          docker push $IMAGE_NAME:$LATEST
          
          #backup
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
          
          docker compose -f $COMPOSE up -d --build
          echo "Restarting service $SERVICE_NAME"

      - name: Health check main
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Running health check on port 9090..."
          trap 'docker image prune -af' EXIT 

          MAX_RETRIES=12 
          RETRY_INTERVAL=5        # 5초 간격
          SUCCESS=0
          
          for i in $(seq 1 $MAX_RETRIES); do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9090/actuator/health || echo "000")
            if [ "$STATUS" -eq 200 ]; then
              echo "Health check passed!"
              SUCCESS=1
              break
            fi  
            echo "Waiting for service...($i/$MAX_RETRIES)"
            sleep $RETRY_INTERVAL
          done

          if [ "$SUCCESS" -ne 1 ]; then
            echo "Health check failed after $((MAX_RETRIES*RETRY_INTERVAL)) seconds"
            echo "===== CONTAINER LOGS START ====="
            CONTAINERS=$(docker compose -f $COMPOSE ps -q)
            for c in $CONTAINERS; do
              echo "--- Logs for container $c ---"
              docker logs --tail 100 $c
            done
            echo "===== CONTAINER LOGS END ====="
            
            echo "Rolling back to previous image..."
            docker compose -f $COMPOSE down
            docker tag $IMAGE_NAME:$BACKUP $IMAGE_NAME:$LATEST
            docker compose -f $COMPOSE up -d
            echo "Rollback completed for $SERVICE_NAME"
            exit 1
          fi
                    
      - name: PR build check
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          echo "Pull Request build for main branch - no deployment"
          cd $TARGET_DIR
          mvn clean package -DskipTests